07_django/base_prj/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns =[
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('signup/', views.signup, name='signup')
]

07_django/base_prj/base_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sns/', include('sns.urls')),
    path('movie/', include('movie.urls')),
    path('accounts/', include('accounts.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

07_django/base_prj/movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns =[
    path('', views.index, name='list'),
    path('create/', views.create, name='create'),

]

07_django/base_prj/sns/urls.py
from django.urls import path
from . import views

# from django.conf.urls.static import static
# from django.conf import settings

app_name = 'sns'

urlpatterns =[
    path('', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('new/', views.create_posting, name='create_posting'),
    path('<int:posting_id>/edit/', views.edit_posting, name='edit_posting'),
    path('<int:posting_id>/delete/', views.delete_posting, name='delete_posting'),
    path('<int:posting_id>/comments/create/', views.create_comment, name='craete_comment')

]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

07_django/base_prj/movie/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_eng = models.CharField(max_length=100)
    audience = models.IntegerField(default=0)
    open_date = models.DateField()
    genre = models.CharField(max_length=100)
    watch_grade = models.CharField(max_length=100)
    score = models.FloatField(default=0.0)
    poster_url = models.TextField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.title}'

07_django/base_prj/sns/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Posting(models.Model):
    content = models.CharField(max_length=500)
    icon = models.CharField(max_length=20, default='fas fa-question')
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content[:10]}...'


class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content}'

07_django/base_prj/movie/forms.py
from django import forms
from .models import Movie


# class MovieForm(forms.Form):
#     title = forms.CharField(max_length=100)
#     title_eng = forms.CharField(max_length=100)
#     audience = forms.IntegerField()
#     open_date = forms.DateField(
#         widget=forms.widgets.DateInput(attrs={'type': 'date'})
#
#     )
#     genre=forms.CharField(max_length=100)
#     watch_grade = forms.CharField(max_length=100)
#     score = forms.FloatField()
#     poster_url = forms.CharField()
#     description = forms.CharField(widget=forms.Textarea())


class MovieModelForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__' # 이렇게 하거나, ['title', 'title_eng'] 이런 식으로 특정 컬럼만 받을 수도 있음.
        widgets ={
            'open_date': forms.DateInput(attrs={'type': 'date'}),
        }

07_django/base_prj/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
# @login_required((login_url='/accounts/signin'))
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:index')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })


def index(request):
    return render(request, 'accounts/index.html')


def signin(request):
    # 이미 로그인 했는데, 다시 로그인을 하려 한다면,
    if request.user.is_authenticated:
        return redirect('accounts:index')
    # 로그인 시켜주세요
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid(): # 검증 성공
            login(request, form.get_user()) # 로그인 하고

            if request.GET.get('next'): # 이전에 있던 페이지가 있다면 거기로 보내고
                return redirect(request.GET.get('next'))
            return redirect('accounts:index') # 없다면 우리가 지정한 페이지로 보낸다.
    # 로그인 화면 주세요
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/signin.html', {
        'form': form,
    })


def signout(request):
    logout(request)
    return redirect('accounts:index')

07_django/base_prj/movie/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie
from .forms import MovieModelForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    return render(request, 'movie/list.html', {
        'movies': movies
    })
@login_required(login_url='/accounts/signin')
def create(request):
    if request.method == 'POST':
        form = MovieModelForm(request.POST)
        if form.is_valid():
            # title = form.cleaned_data.get('title')
            # title_eng = form.cleaned_data.get('title_eng')
            # audience = form.cleaned_data.get('audience')
            # open_date = form.cleaned_data.get('open_date')
            # genre = form.cleaned_data.get('genre')
            # watch_grade = form.cleaned_data.get('watch_grade')
            # score = form.cleaned_data.get('score')
            # poster_url = form.cleaned_data.get('poster_url')
            # description = form.cleaned_data.get('description')
            #
            # Movie.objects.create(
            #     title = title,    title_eng = title_eng,         audience = audience,          open_date = open_date,        genre = genre,       watch_grade = watch_grade,
            #     score = score,
            #     poster_url = poster_url,
            #     description = description,
            #
            #
            # )
            form.save()
            return redirect('movie:list')
    else:
        form = MovieModelForm()

    return render(request, 'movie/create.html', {
        'form':form,


    })

def update(request, id):
    movie = get_object_or_404(Movie, id=id)
    if request.method=='POST':
        form = MovieModelForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movie:detail', id)
    else:
        form = MovieModelForm(instance=movie)
    return render(request, 'movie/update.html', {
        'form':form,
    })

07_django/base_prj/sns/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Posting, Comment


def posting_list(request):
    postings = Posting.objects.all()

    return render(request, 'sns/list.html', {
        'postings': postings,

    })


def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comments = posting.comment_set.all()

    return render(request, 'sns/detail.html', {
        'posting': posting,
        'comments': comments,
    })


def create_posting(request):
    if request.method=='POST':
        posting = Posting()
        posting.content = request.POST.get('content')
        posting.icon = request.POST.get('icon')
        posting.image = request.FILES.get('image')
        posting.save()
        return redirect('sns:posting_detail', posting.id)
    else:
        return redirect('sns:posting_list')



def edit_posting(request):
    pass


def delete_posting(request):
    pass


def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if request.method == 'POST':
        comment = Comment()
        comment.content =request.POST.get('comment')
        comment.posting = posting
        comment.save()
        return redirect('sns:posting_detail', posting_id)

07_django/base_prj/accounts/templates/accounts/index.html
<h1>회원가입과 로그인 테스트</h1>

<h2>
    {% if user.is_authenticated %}
        You are Logged In <a href="{% url 'accounts:signout' %}">로그아웃 하러가기</a>
    {% else %}
        You are Not Logged In <a href="{% url 'accounts:signin' %}">로그인 하러가기</a>
    {% endif %}
</h2>

07_django/base_prj/accounts/templates/accounts/signin.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">

</form>

07_django/base_prj/accounts/templates/accounts/signup.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

07_django/base_prj/movie/templates/movie/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django Form with MOVIE</title>
</head>
<body>
{% block body %}

{% endblock %}

</body>
</html>

07_django/base_prj/movie/templates/movie/create.html
{% extends 'movie/base.html' %}

{% block body %}
    <form action="#" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">

    </form>

{% endblock %}

07_django/base_prj/sns/templates/sns/_header.html
<header class="mt-3">
        <form action="{% url 'sns:create_posting' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- icon select tag -->
            <div class="form-row align-items-center">
                <div class="col-auto my-1">
                    <label for="icon" class="sr-only">icon</label>
                    <select name="icon" id="icon" class="custom-select mr-sm-2">
                        <option value="fas fa-question">?</option>
                        <option value="far fa-smile">:)</option>
                        <option value="far fa-angry">:(</option>
                        <option value="far fa-smile-wink">;)</option>
                        <option value="far fa-tired">:|</option>
                    </select>
                </div>
                <!-- content input tag  -->
                <div class="col-sm-6 my-1">
                    <label for="content" class="sr-only">content</label>
                    <input type="text" name="content" class="form-control" placeholder="Feels like..">
                </div>

                <!-- image file input tag -->
                <div class="col-sm-4 my-1 input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Upload</span>
                    </div>
                    <div class="custom-file">
                        <input id="image" name="image" accept="image/*" type="file">
                        <label for="image" class="custom-file-label">Choose image</label>
                    </div>
                </div>

                <!-- submit -->
                <div class="col-auto my-1">
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </div>
        </form>
</header>

07_django/base_prj/sns/templates/sns/_nav.html
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a href="{% url 'sns:posting_list' %}" class="nav-link {% block list %}{% endblock %}">I'm feeling lucky</a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% block detail %}{% endblock %}" aria-disabled="true">Detail</a>
    </li>
</ul>

07_django/base_prj/sns/templates/sns/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>My SNS</title>
</head>
<body>
    {% include 'sns/_nav.html' %}

    <div class="container">
        {% block body %}
        {% endblock %}
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

07_django/base_prj/sns/templates/sns/detail.html
{% extends 'sns/base.html' %}
{% block detail %}active{% endblock %}

{% block body %}
    <div class="row mt-3">
        <div class="col-12 col-md-6">
            <div class="card">
                {% if posting.image %}
                    <img src="{{ posting.image.url }}" class="card-img-top image-fluid" alt="{{ posting.image }}">
                {% else %}
                    <img src="http://lorempixel.com/300/200" alt="random image" class="card-image-top img-fluid">
                {% endif %}

                <div class="card-body">
                    <i class="{{ posting.icon }}"></i>
                    <hr>
                    <p class="card-text">{{ posting.content }}</p>
                </div>
            </div>

            <div class="card mt-2">
                <div class="card-body">
                    <form action="{% url 'sns:craete_comment' posting.id %}" method="POST">
                        {% csrf_token %}
                        <label for="comment">leave comment</label>
                        <input type="text" name="comment" id="comment" class="form-control">
                    </form>
                </div>
            </div>
        </div>


        <div class="col-12 col-md-6">
            <div class="card">
                <ul class="list-group list-group-flush">
                    {% if comments %}
                        {% for comment in comments %}
                            <li class="list-group-item mb-1">{{ comment.content }}</li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item mb-1">No comments yet..</li>

                    {% endif %}
                </ul>
            </div>

        </div>
    </div>

{% endblock %}

07_django/base_prj/sns/templates/sns/list.html
{% extends 'sns/base.html' %}
{% block list %}active{% endblock %}

{% block body %}
    {% include 'sns/_header.html' %}
    <hr>
    {% if postings %}
        <section class="card-columns">
            {% for posting in postings %}

                <article class="card mb-2">
                    <a href="{% url 'sns:posting_detail' posting.id %}">
                        {% if posting.image %}

                            <img src="{{ posting.image.url }}" class="card-img-top" alt="{{ posting.image }}">
                        {% else %}
                            <img src="http://lorempixel.com/150/75" alt="random_image_{{ forloop.counter }}"
                                 class="card-img-top">
                        {% endif %}

                    </a>
                    <div class="card-body">
                        {% if posting.comment_set.count < 5 %}
                            {% for i in posting.comment_set.all %}

                                <i class="{{ posting.icon }} fa-3x"></i>
                            {% endfor %}
                        {% else %}
                            <i class="{{ posting.icon }} fa-3x"> x {{ posting.comment_set.count }}</i>
                        {% endif %}


                    </div>
                </article>

            {% endfor %}

        </section>

    {% endif %}

{% endblock %}