07_django/INSTA/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns =[
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('users/<str:username>/', views.user_detail, name='user_detail'),
    path('follow/<str:username>/', views.toggle_follow, name='toggle_follow'),
]

07_django/INSTA/insta/urls.py
from django.contrib import admin
from django.urls import path, include

# media 업로드를 위해서
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('insta/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

07_django/INSTA/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create/', views.create_post, name='create_post'),
    path('<int:post_id>/update/', views.update_post, name='update_post'),
    path('<int:post_id>/comment/', views.create_comment, name='create_comment'),
    path('<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    path('tags/<str:tag_name>/', views.tag_posts_list, name='tag_posts_list')
]

07_django/INSTA/posts/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser

from faker import Faker
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
faker = Faker()


class Hashtag(models.Model):
    content = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.content


class Post(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)

    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    tags = models.ManyToManyField(Hashtag, blank=True, related_name='posts')

    @classmethod
    def dummy(cls, n):
        for _ in range(n):
            Post.objects.create(content=faker.text(130))


class Image(TimeStampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
        blank=True,
        upload_to='posts/images',
        processors=[ResizeToFill(600, 600)],
        format='JPEG',
        options={'quality': 90, }
    )


class Comment(TimeStampedModel):
    content = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

07_django/INSTA/posts/forms.py
from django import forms
from .models import Post, Image, Comment


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', ]


class ImageModelForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['file', ]
        widgets = {
            'file': forms.FileInput(attrs={'multiple': True})
        }


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', ]

07_django/INSTA/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import Post, Image, Hashtag
from django.views.decorators.http import require_GET, require_http_methods, require_POST
from .forms import PostModelForm, ImageModelForm, CommentModelForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponseBadRequest


@login_required
@require_http_methods(['GET', 'POST'])
def create_post(request):
    # POST 방식으로 넘온 Data 를 ModelForm 에 넣는다.
    if request.method == 'POST':
        # POST 방식으로 넘온 Data 를 ModelForm 에 넣는다.
        post_form = PostModelForm(request.POST)
        # Data 검증을 한다.
        if post_form.is_valid():

            # 통과하면 저장한다.
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()

            #create hashtag
            content = post_form.cleaned_data.get('content')
            words = content.split() #띄어쓰기 기준 split
            for word in words:
                if word[0] == '#':
                    word = word[1:]
                    tag = Hashtag.objects.get_or_create(content=word)
                    post.tags.add(tag[0])
                    if tag[1]:
                        messages.add_message(request, messages.SUCCESS, f'{tag[0]} 태그를 처음으로 추가하셨서요') # 태그가 처음 만들어졌을 경우


            for image in request.FILES.getlist('file'):
                request.FILES['file'] = image
                image_form = ImageModelForm(files=request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.post = post
                    image.save()

            return redirect('posts:post_list')
        else:
            # 실패하면, 다시 data 입력 form 을 준다.
            pass
    # GET 방식으로 요청이 오면,
    else:
        post_form = PostModelForm()
    image_form = ImageModelForm()
    return render(request, 'posts/form.html', {
        'post_form': post_form,
        'image_form': image_form,

    })


@require_GET
def post_list(request):
    posts = Post.objects.all()
    user = request.user
    comment_form = CommentModelForm()
    return render(request, 'posts/list.html', {
        'posts': posts,
        'user': user,
        'comment_form': comment_form,
    })


@login_required
@require_http_methods(['POST'])
def create_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentModelForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/insta/'))
    # FIXME else:




@login_required
@require_http_methods(['GET', 'POST'])
def update_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.user == request.user: # 지금 수정하려는 포스트 작성자가 요청 보낸 사람이라면,
        if request.method == 'POST':
            post_form = PostModelForm(request.POST, instance=post)
            if post_form.is_valid():
                post_form.save()
                #update hashtag
                post.tags.clear()
                # create hashtag
                content = post_form.cleaned_data.get('content')
                words = content.split()  # 띄어쓰기 기준 split
                for word in words:
                    if word[0] == '#':
                        word = word[1:]
                        tag = Hashtag.objects.get_or_create(content=word)
                        post.tags.add(tag[0])
                        if tag[1]:
                            messages.add_message(request, messages.SUCCESS,
                                                 f'{tag[0]} 태그를 처음으로 추가하셨서요')  # 태그가 처음 만들어졌을 경우
                return redirect('posts:post_list')

        else:
            post_form = PostModelForm(instance=post)
        return render(request, 'posts/form.html', {
            'post_form': post_form
        })
    # 작성자와 요청 보낸 유저가 다르다면,
    else:
        return redirect('posts:post_list')


# def create_like(request, post_id):
#     user = request.user
#     post = get_object_or_404(Post, id=post_id)
#     post.like_users.add(user)

@login_required
@require_http_methods(['POST'])
def toggle_like(request, post_id):
    if request.is_ajax():
        user = request.user
        post = get_object_or_404(Post, id=post_id)
        is_active = True
        # if post.like_users.filter(id=user.id): ORM 버전. 밑에 건, 걍 파이썬문법 버전.
        if user in post.like_users.all():
            post.like_users.remove(user)
            is_active = False
        else:
            post.like_users.add(user)
            is_active = True
        return JsonResponse({
            'likeCount': post.like_users.count(),
            'is_active': is_active

        })
    else:
        return HttpResponseBadRequest()

@require_GET
def tag_posts_list(request, tag_name):
    tag = get_object_or_404(Hashtag, content=tag_name)
    posts = tag.posts.all()
    return render(request, 'posts/list.html', {
        'posts': posts,
    })

07_django/INSTA/posts/templates/posts/_post.html
<div class="card my-3">
    {% if post.image_set.all %}
        <div id="post{{ post.id }}" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                {% for image in post.image_set.all %}
                    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                        <img src="{{ image.file.url }}" class="d-block w-100" alt="{{ image.file }}">
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#post{{ post.id }}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#post{{ post.id }}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    {% else %}
        <img src="https://picsum.photos/600/?random" alt="random-image" class="card-img-top"/>
    {% endif %}

    <div class="card-body">
        {% if user == post.user %}
            <p class="card-text">
                {{ post.user }} // {{ post.content }}
                <a href="{% url 'posts:update_post' post.id %}" class="text-">수정</a>

            </p>

        {% else %}
            <p class="card-text"><a href="{% url 'accounts:user_detail' post.user.username %}">{{ post.user }}</a> // {{ post.content }} </p>
        {% endif %}

    </div>
    <div class="card-body">
<!-- 좋아요 -->
{#        <form action="{% url 'posts:toggle_like' post.id %}" method="POST">#}
{#            {% csrf_token %}#}
{#            {% if user in post.like_users.all %}#}
{#                <input type="submit" class="btn btn-light" value="좋아요 취소">#}
{#                {% else %}#}
{#                <input type="submit" class="btn btn-light" value="좋아요">#}
{#            {% endif %}#}
{#            <a window.location.href="{% url 'posts:update_post' post_id %}"></a>#}
{#        </form>#}

{#    좋아요 버튼 2#}
    {% if user in post.like_users.all %}
        <i class="fas fa-thumbs-up fa-2x activate like-button" data-id="{{ post.id }}"></i>
    {% else %}
        <i class="fas fa-thumbs-up fa-2x like-button" data-id="{{ post.id }}"></i>
    {% endif %}
    <p class="card-text">좋아요 <span id="like-count-{{ post.id }}">{{ post.like_users.count }}</span>개</p>

    </div>

    <div class="card-body">
    <p class="card-text">
        {% for comment in post.comment_set.all %}

            <p><strong>{{ comment.user }}</strong> : {{ comment.content }}</p>

        {% empty %}
            <p>댓글을 달아주세요</p>
        {% endfor %}
    </p>
    </div>
    <div class="card-footer">
        <form action="{% url 'posts:create_comment' post.id %}" method="POST">
            {% csrf_token %}
            {{ comment_form.content }}
            <input type="submit" class="btn btn-light" value="댓글 달기">

        </form>
    </div>

</div>

07_django/INSTA/posts/templates/posts/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
    <h1>new_post</h1>
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
    </form>
{% endblock %}

07_django/INSTA/posts/templates/posts/list.html
{% extends 'base.html' %}

{% block body %}
    <h1>Posts</h1>


    <section class="card-columns">
        {% for post in posts %}
            {% include 'posts/_post.html' with post=post comment_form=comment_form %}

        {% endfor %}

    </section>



{% endblock %}