07_django/review_prj/board/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('index/', views.index),
    path('greeting/<str:name>/<str:role>/', views.greeting),

    path('articles/new/', views.article_new),
    path('articles/create/', views.article_create),
    path('articles/', views.article_list),
    path('articles/<int:id>/', views.article_detail),
    path('articles/<int:id>/edit/', views.article_edit),
    path('articles/<int:id>/delete/', views.article_delete),
    path('articles/<int:id>/update/', views.article_update),

]

07_django/review_prj/board_ad/urls.py
from django.urls import path
from . import views

app_name = 'board_ad'

urlpatterns = [
    path('', views.posting_list, name='posting_list'),
    path('<int:post_id>/', views.posting_detail, name='posting_detail'),
    path('new/', views.new_posting, name='new_posting'),
    path('<int:post_id>/update/', views.update_posting, name='update_posting'),
    path('<int:post_id>/delete/', views.delete_posting, name='delete_posting'),
    path('<int:posting_id>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:posting_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
]

07_django/review_prj/review_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('postings/', include('board_ad.urls')),
]

07_django/review_prj/board/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()


    def __str__(self):
        return f'{self.id}: {self.title}'


# Create your models here.

07_django/review_prj/board_ad/models.py
from django.db import models
import datetime


class Posting(models.Model):
    title = models.CharField(max_length=200, default='')
    content = models.TextField(default='CONTENT')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.title[:20]}'


class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=200, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}: {self.content[:30]}'

# Create your models here.

07_django/review_prj/board/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.


def article_new(request):
    return render(request, 'board_ad/new.html')



def article_create(request):
    article = Article()
    article.title = request.POST.get('input_title')
    article.content = request.POST.get('input_content')
    article.save()

    return redirect(f'/board_ad/articles/{article.id}/')


def article_list(request):
    articles = Article.objects.all()
    return render(request, 'board_ad/list.html', {
        'articles': articles,
    })



def article_detail(request, id):

    article = Article.objects.get(id=id)
    return render(request, 'board_ad/detail.html', {
        'article':article,

    })



def article_edit(request, id):
    article = Article.objects.get(id=id)

    return render(request, 'board_ad/edit.html', {'article':article})


def article_update(request, id):
    article = Article.objects.get(id=id)
    article.title = request.POST.get('input_title')
    article.content = request.POST.get('input_content')
    article.save()
    return redirect(f'/board_ad/articles/{article.id}')
    pass


def article_delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect('/board_ad/articles/')
    pass









def index(request):

    return render(request, 'board_ad/index.html')

def greeting(request, name, role):
    if role == 'admin':
        return render(request, 'board_ad/greeting.html', {

            'role': 'MASTER USER',
            'name': name.upper(),
        })
    else:
        return render(request, 'board_ad/greeting.html', {
            'name': name,
            'role': role,
        })

07_django/review_prj/board_ad/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Posting, Comment
from django.http import HttpResponseBadRequest
from django.views.decorators.http import require_http_methods


def posting_list(request):
    posts = Posting.objects.all()
    return render(request, 'board_ad/list.html', {'posts': posts})


def posting_detail(request, post_id):

    post = get_object_or_404(Posting, id=post_id)
    comments = post.comment_set.all()

    return render(request, 'board_ad/detail.html', {
        'post': post,
        'comments': comments,


        })


def new_posting(request):
    if request.method == 'GET':
        return render(request, 'board_ad/new.html')
    else:
        post = Posting()
        post.title = request.POST.get('input_title')
        post.content = request.POST.get('input_content')
        post.save()
        return redirect('board_ad:posting_detail', post.id)


def update_posting(request, post_id):
    post = get_object_or_404(Posting, id=post_id)
    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')
        post.save()
        return redirect('board_ad:posting_detail', post.id)
    else:
        return render(request, 'board_ad/edit.html', {'post': post})


@require_http_methods(['POST'])
def delete_posting(request, post_id):
    post = get_object_or_404(Posting, id=post_id)
    post.delete()
    return redirect('board_ad:posting_list')

#comment - create
@require_http_methods(['POST'])
def create_comment(request, posting_id):
    comment = Comment()
    comment.content = request.POST.get('input_comment')
    comment.posting_id = posting_id
    comment.save()
    return redirect('board_ad:posting_detail', posting_id)


def delete_comment(request, posting_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('board_ad:posting_detail', posting_id)

07_django/review_prj/templates/board/greeting.html
{% extends 'board/base.html' %}


{% block body %}

    <h1>Hello {{ name }}</h1>
    <p>You are {{ role }}</p>

{% endblock %}

07_django/review_prj/templates/board/index.html
{% extends 'board/base.html' %}

{% block body %}
    <h1>hello </h1>

{% endblock %}

07_django/review_prj/templates/board_ad/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}


    {% endblock %}
</body>
</html>

07_django/review_prj/templates/board_ad/detail.html
{% extends 'board_ad/base.html' %}

{% block body %}

    <h1>{{ post.title }}</h1>

    <p>{{ post.content }}</p>
    <hr>
    <a href="{% url 'board_ad:posting_list' %}"><button>List</button></a>
    <a href="{% url 'board_ad:update_posting' post.id %}"><button>Edit</button></a>
    <form action="{% url 'board_ad:delete_posting' post.id %}" method="POST">
    {% csrf_token %}
        <button type="submit" onclick="return confirm('확인');">Delete</button>
    <button id="reset">WOW</button>
        <script>
            button=document.querySelector('#reset')
            button.addEventListener('click', (e) => {
                document.write('<h1>hahaha</h1>')
            });
        </script>
    </form>

    <hr>
    {% if comments %}
        <ul>
        {% for comment in comments %}
            <li>
             {{ comment.content }}
                <form action="{% url 'board_ad:delete_comment' posting_id=post.id comment_id=comment.id %}" method="POST">
                    {% csrf_token %}
                    <button>삭째</button>
                </form>
            </li>
        {% endfor %}

        </ul>

    {% endif %}




    <form action="{% url 'board_ad:create_comment' post.id %}" method="POST">
    {% csrf_token %}
        <label for="comment"></label>
        <input type="text" id="comment" name="input_comment">
        <input type="submit" value="대끌쓰기">
    </form>
{% endblock %}

07_django/review_prj/templates/board_ad/edit.html
{% extends 'board_ad/base.html' %}

{% block body %}

<form action="{% url 'board_ad:update_posting' post.id %}" method="POST">
    {% csrf_token %}

    <input type="text" name="title" value="{{ post.title }}">

    <textarea name="content" cols="30" rows="10" >{{ post.content }}</textarea>

    <button type="submit">Create</button>

</form>

{% endblock %}

07_django/review_prj/templates/board_ad/greeting.html
{% extends 'board_ad/base.html' %}


{% block body %}

    <h1>Hello {{ name }}</h1>
    <p>You are {{ role }}</p>

{% endblock %}

07_django/review_prj/templates/board_ad/index.html
{% extends 'board_ad/base.html' %}

{% block body %}
    <h1>hello </h1>

{% endblock %}

07_django/review_prj/templates/board_ad/list.html
{% extends 'board_ad/base.html' %}

{% block body %}

    <h1>Post List</h1>

    <a href="{% url 'board_ad:new_posting' %}"><button>new</button></a>

    {% if posts %}

    <ul>
        {% for post in posts %}
            <li>

                <a href="{% url 'board_ad:posting_detail' post.id %}">{{ post.title }}</a>

            </li>
        {% endfor %}
    </ul>

    {% endif %}
{% endblock %}

07_django/review_prj/templates/board_ad/new.html
{% extends 'board_ad/base.html' %}

{% block body %}

<form action="{% url 'board_ad:new_posting' %}" method="POST">
    {% csrf_token %}
    <div>
    <label for="title">Title</label>
    <input type="text" id="title" name="input_title">
    </div>
    <div>
    <label for="content">Content</label>
    <textarea name="input_content" id="content" cols="30" rows="10" ></textarea>
    </div>
    <div>
        <button type="submit">Create</button>
    </div>
</form>

{% endblock %}